## Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
%%timeit

L = list(range(1000000))
for _ in range(10): L2 = [i*2 for i in L]

754 ms ± 58.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit

arr = np.arange(1000000)
for _ in range(10): arr2 = arr * 10

16.8 ms ± 407 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
arr = np.array([1,2,3,4,5,9.5])
arr

array([1. , 2. , 3. , 4. , 5. , 9.5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

float64
(6,)
1


In [7]:
arr = np.array([1,2,3,4], dtype=np.uint8)
arr2 = np.array([1,2,3,4], dtype="u2")

print(arr, arr.dtype)
print(arr2, arr2.dtype)



[1 2 3 4] uint8
[1 2 3 4] uint16


In [8]:
arr3 = np.array(["1","2","3","4"], dtype=np.uint8)
print(arr3, arr3.dtype)

[1 2 3 4] uint8


In [10]:
arr = np.array([1,"2",3,4,5+8j,9.5])
arr

array(['1', '2', '3', '4', '(5+8j)', '9.5'], dtype='<U64')

In [11]:
t = np.zeros((5,6))
t

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
t = np.empty((5,6))
t

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
t2 = np.full_like(t, fill_value=5)
t2

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [16]:
arr = np.random.randint(1,20, 25)
arr

array([ 8, 11, 14, 10, 11, 10, 11, 14, 12, 13,  6, 15, 13,  7, 13, 14, 10,
       10, 11, 17,  4,  7,  2,  4,  6])

In [17]:
arr2 = arr + 10
arr2

array([18, 21, 24, 20, 21, 20, 21, 24, 22, 23, 16, 25, 23, 17, 23, 24, 20,
       20, 21, 27, 14, 17, 12, 14, 16])

In [20]:
arr2 > 15

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False, False,  True])

In [21]:
arr = np.random.randint(1,20, 20)
arr

array([14,  6,  6,  5, 11, 15, 18,  9,  4,  5,  7,  4,  7, 18, 14, 14, 10,
       11, 16,  1])

In [22]:
arr2 = np.random.randint(1,20, 20)
arr2

array([12,  9,  5,  3, 19,  1,  5, 16, 10, 12,  9, 11, 16,  3,  9,  3, 18,
       11,  6, 19])

In [23]:
np.maximum(arr, arr2)

array([14,  9,  6,  5, 19, 15, 18, 16, 10, 12,  9, 11, 16, 18, 14, 14, 18,
       11, 16, 19])

In [24]:
np.minimum(arr, arr2)

array([12,  6,  5,  3, 11,  1,  5,  9,  4,  5,  7,  4,  7,  3,  9,  3, 10,
       11,  6,  1])

In [25]:
(arr2 > 10).sum()

9

In [26]:
arr2[arr2 > 10]

array([12, 19, 16, 12, 11, 16, 18, 11, 19])

In [27]:
arr2[(arr2 > 5) & (arr2 < 10)]

array([9, 9, 9, 6])

In [28]:
arr2[arr2 > 10]=10
arr2

array([10,  9,  5,  3, 10,  1,  5, 10, 10, 10,  9, 10, 10,  3,  9,  3, 10,
       10,  6, 10])

In [29]:
m = np.random.randint(1,50, 25).reshape(5,-1)
m

array([[ 2, 34, 21,  9, 46],
       [30, 18, 47,  2,  3],
       [17, 26, 10, 35, 22],
       [37, 10, 27, 13,  4],
       [38,  8, 15,  3, 35]])

In [30]:
m[1:-1,1:-1]

array([[18, 47,  2],
       [26, 10, 35],
       [10, 27, 13]])

In [31]:
m[[True, True, False, False, False]]

array([[ 2, 34, 21,  9, 46],
       [30, 18, 47,  2,  3]])

In [32]:
m[[1,3,0]]

array([[30, 18, 47,  2,  3],
       [37, 10, 27, 13,  4],
       [ 2, 34, 21,  9, 46]])

In [33]:
m

array([[ 2, 34, 21,  9, 46],
       [30, 18, 47,  2,  3],
       [17, 26, 10, 35, 22],
       [37, 10, 27, 13,  4],
       [38,  8, 15,  3, 35]])

In [34]:
np.where(m>30,30,m)

array([[ 2, 30, 21,  9, 30],
       [30, 18, 30,  2,  3],
       [17, 26, 10, 30, 22],
       [30, 10, 27, 13,  4],
       [30,  8, 15,  3, 30]])

In [35]:
m.sum()

512

In [36]:
m.sum(axis=0)

array([124,  96, 120,  62, 110])

In [37]:
m.sum(axis=1)

array([112, 100, 110,  91,  99])

In [39]:
m = np.random.randint(1,50, 25)
print(m)
np.cumsum(m)

[23 42 24 25 44 32 20 32 27 44 26 40 22 36 27  5  8 25  3 19 31 36 25  8
 45]


array([ 23,  65,  89, 114, 158, 190, 210, 242, 269, 313, 339, 379, 401,
       437, 464, 469, 477, 502, 505, 524, 555, 591, 616, 624, 669],
      dtype=int32)

In [40]:
x = np.random.randint (0, 50, 1000)
y = x + np.random.normal (0, 10, 1000)

t = np.corrcoef(x,y)

In [41]:
t

array([[1.        , 0.80572369],
       [0.80572369, 1.        ]])

In [42]:
round(t[1][0] * 100,2)

80.57

In [43]:
m

array([23, 42, 24, 25, 44, 32, 20, 32, 27, 44, 26, 40, 22, 36, 27,  5,  8,
       25,  3, 19, 31, 36, 25,  8, 45])

In [45]:
np.any(m>30)

True

In [46]:
np.all(m>30)

False

In [47]:
m = np.random.randint(1,50,200).reshape(20,-1)
m

array([[22,  9, 48, 36, 45, 39, 45,  3, 18, 30],
       [13,  7, 20,  3, 16,  3, 38, 16, 10, 12],
       [23, 10, 37,  7, 44, 11, 45, 32, 42, 24],
       [34,  2, 28,  6, 13,  7,  9,  4, 16,  4],
       [ 7, 18, 20, 22,  9, 39, 39, 49, 35, 13],
       [ 3,  8, 28, 18,  7, 48, 13, 27, 37, 15],
       [49, 45, 27, 49, 10, 30, 20, 47, 29, 26],
       [10, 27, 46, 38, 49,  7, 13, 21, 24, 14],
       [14, 22, 28, 31,  2, 32, 28, 43,  8, 28],
       [ 4, 18, 21,  2, 16, 23,  5, 21,  4,  9],
       [25, 33, 32,  5, 10, 39, 25, 18, 48, 37],
       [25, 11,  3, 42, 35,  6, 27, 20, 38,  1],
       [21, 20, 39,  7, 49, 36,  5, 18, 41,  1],
       [28, 33, 49, 39, 44, 26, 37, 49, 18, 38],
       [16, 17, 28, 19, 19, 14, 32, 23, 44, 20],
       [ 9,  1, 41,  1, 48,  3,  2, 42, 33, 39],
       [45, 18, 40, 32,  6, 27, 10, 35, 23, 32],
       [16, 21, 19, 21, 12, 41, 20,  9,  2, 19],
       [ 4, 26, 22, 14, 11, 25,  4,  9, 11,  7],
       [12,  7, 44, 15, 36, 37, 38,  9, 32, 28]])

In [54]:
np.savetxt("../ficheros/matriz.csv", m, delimiter=';', fmt="%d")

In [55]:
m = np.random.randint(1,50,200).reshape(20,-1)
m = m * 0.75
m

array([[20.25,  7.5 , 32.25, 27.  ,  2.25,  6.  , 23.25, 27.75,  0.75,
        17.25],
       [14.25,  7.5 , 18.  , 21.  , 31.5 , 27.  , 21.  , 15.75, 33.  ,
        25.5 ],
       [30.75, 24.  ,  9.  , 21.75, 15.75,  6.75,  2.25, 12.75,  0.75,
        15.75],
       [10.5 ,  5.25, 30.  , 20.25, 11.25, 30.75,  9.75,  6.75, 11.25,
        22.5 ],
       [15.  , 24.75,  9.75, 18.75, 33.  ,  9.  , 27.75,  7.5 , 13.5 ,
        18.  ],
       [12.  , 20.25, 34.5 , 26.25,  7.5 , 27.75,  6.  ,  5.25, 28.5 ,
        34.5 ],
       [18.75,  7.5 , 13.5 , 30.  ,  9.  ,  8.25,  9.  , 24.75, 10.5 ,
        33.  ],
       [30.75, 23.25,  9.75, 18.  , 35.25, 30.75,  9.75,  7.5 , 33.  ,
        28.5 ],
       [23.25, 21.  , 30.75, 34.5 , 34.5 , 21.  , 22.5 ,  5.25,  0.75,
        12.  ],
       [ 2.25, 21.75, 18.75,  6.75,  1.5 , 11.25,  0.75,  5.25, 19.5 ,
        27.  ],
       [15.75, 36.75,  9.  , 19.5 , 23.25, 15.  , 33.75, 31.5 , 11.25,
         4.5 ],
       [26.25, 27.75, 10.5 , 35.25, 18.  , 

In [56]:
np.savetxt("../ficheros/matriz.csv", m, delimiter=';', fmt="%.2f")

PermissionError: [Errno 13] Permission denied: '../ficheros/matriz.csv'